version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET=ad1ab216b05099b4256b1c2a2239a15d
      - SALT=ca47801bd17cf3f0157a1951a9427212
      - STRIPE_SECRET_KEY=sk_test_51R8vJQFT1K3803usmkWDpB52eiJvySeN2TKXnxtQ1UUzDxOgylJ3j3pLFySA6HOz2IHpqAGX7srJECsj3nTQTCSs00il22C4JH
      - DB_NAME=fyp-db
      - DB_USER=admin1
      - DB_PASSWORD=FYPdb2025
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DIALECT=mysql
    depends_on:
      - mysql
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=fyp-db
      - MYSQL_USER=admin1
      - MYSQL_PASSWORD=FYPdb2025
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
